// All content lives here — easy to swap out for DB fetches later
const { IconGlobe, IconBraces, IconGauge, IconDatabase, IconFlask, IconBug, IconLock, IconLayers, IconGitBranch, IconClock, IconSparkle } = window.Icons;

window.DATA = {
  nav: [
    { id: 'work', label: 'Work' },
    { id: 'skills', label: 'Skills' },
    { id: 'performance', label: 'Performance' },
    { id: 'notes', label: 'Notes' },
    { id: 'contact', label: 'Contact' },
  ],

  skills: [
    {
      icon: IconGlobe,
      category: 'Web / UI',
      tools: [
        { name: 'Selenium WebDriver', level: 95 },
        { name: 'Cucumber / BDD', level: 82 },
        { name: 'JUnit / TestNG', level: 88 },
        { name: 'Playwright', level: 65 },
      ],
    },
    {
      icon: IconBraces,
      category: 'API',
      tools: [
        { name: 'Postman / Newman', level: 92 },
        { name: 'Swagger / OpenAPI', level: 80 },
        { name: 'Rest-Assured', level: 74 },
        { name: 'SoapUI', level: 62 },
      ],
    },
    {
      icon: IconGauge,
      category: 'Performance',
      tools: [
        { name: 'Apache JMeter', level: 90 },
        { name: 'Grafana / InfluxDB', level: 72 },
        { name: 'k6', level: 60 },
        { name: 'Gatling', level: 45 },
      ],
    },
    {
      icon: IconDatabase,
      category: 'Tools & CI/CD',
      tools: [
        { name: 'JIRA / TestRail', level: 92 },
        { name: 'Git / GitHub / GitLab', level: 85 },
        { name: 'GitLab CI/CD', level: 75 },
        { name: 'SQL', level: 80 },
      ],
    },
  ],

  projects: [
    {
      id: 'azericard-tezode',
      index: '01',
      name: 'TezÖdə Payment Platform',
      stack: ['Selenium WebDriver', 'Java', 'JUnit', 'TestNG', 'JMeter', 'Postman'],
      description: 'Automation and manual testing for TezÖdə web application at Azericard — Azerbaijan\'s national processing center. Regression, functional, API and performance testing for banking integrations supporting American Express, UnionPay and 17 international banks.',
      metric: 'Regression + API + performance coverage for 17+ bank integrations',
      metricDelta: '17+ banks',
      status: 'Production',
      repo: 'Azericard — internal / NDA',
      primaryTag: 'Fintech',
    },
    {
      id: 'codelab-erp',
      index: '02',
      name: 'ERP Systems Automation',
      stack: ['Java', 'Selenium WebDriver', 'JUnit', 'TestNG', 'Postman', 'SQL'],
      description: 'Led test automation for Studio and Kometa ERP systems at Code Lab Azerbaijan. Manual and API testing using Swagger, Postman, and SQL to ensure robust integration and data accuracy. Defect tracking in JIRA within an Agile Scrum framework.',
      metric: 'Automated regression across 3 enterprise systems',
      metricDelta: '3 systems',
      status: 'Production',
      repo: 'Code Lab Azerbaijan — internal',
      primaryTag: 'ERP',
    },
    {
      id: 'bestcomp-gov',
      index: '03',
      name: 'Government & E-Commerce QA',
      stack: ['JIRA', 'TestRail', 'SoapUI', 'Postman', 'Bugzilla', 'Selenium WebDriver'],
      description: 'Manual QA for Mashin.al, Texnika.al, State Treasury (DXA) and Bestcomp websites at Bestcomp Azerbaijan. Structured test execution using TestRail, defect tracking in JIRA and Bugzilla, API validation with SoapUI. Ensured functionality, usability and security of government-facing portals.',
      metric: 'QA coverage across 4 platforms including govt State Treasury (DXA)',
      metricDelta: '4 platforms',
      status: 'Production',
      repo: 'Bestcomp Azerbaijan — internal',
      primaryTag: 'Gov / E-Com',
    },
    {
      id: 'perf-suite',
      index: '04',
      name: 'API & Load Testing Suite',
      stack: ['JMeter', 'InfluxDB', 'Grafana', 'Postman', 'Docker'],
      description: 'Performance and API testing stack used across Azericard and Plus Azerbaijan. JMeter distributed load tests modelling real traffic shapes — ramp, spike, soak. Live Grafana dashboards per service. Validated full system stability under concurrent load for banking and ERP platforms.',
      metric: 'Sustained 5,200 VUs @ p95 < 480ms',
      metricDelta: '5.2k VU',
      status: 'Active',
      repo: 'Multi-project — internal',
      primaryTag: 'Load',
    },
    {
      id: 'vpos-simulator',
      index: '05',
      name: 'ISO 8583 VPOS Terminal Simulator',
      stack: ['ISO 8583', 'TCP/IP Sockets', 'JavaScript', 'ISO 9564', 'Bitmap Parser'],
      description: 'Browser-based Virtual POS terminal simulator built during my time at Azericard. Implements raw TCP/IP ISO 8583 messaging with a hand-written bitmap parser/packer, ISO 9564 Format-0 PIN block generation, and full LMK/TPK/TAK key management concepts. Covers Purchase (0200), Reversal (0400) and Settlement (0500) transaction flows with live field-by-field message logging.',
      metric: 'Full Purchase · Reversal · Settlement lifecycle over raw TCP/IP',
      metricDelta: '3 flows',
      status: 'Prototype',
      repo: 'Azericard — internal research',
      primaryTag: 'Fintech',
      featured: true,
    },
  ],

  tips: [
    {
      tag: 'Selectors',
      icon: IconBug,
      title: 'Stop locating by CSS class',
      body: 'CSS classes shift with every design pass. Anchor on role, accessible name, or a dedicated data-testid. Your test suite stops breaking for cosmetic reasons.',
      read: '2 min',
    },
    {
      tag: 'Flakiness',
      icon: IconClock,
      title: 'Replace sleep() with explicit waits',
      body: 'Thread.sleep() is a bet. WebDriverWait.until(condition) is a contract. Half of all flakes I have triaged in 3 years trace back to hard sleeps hiding real race conditions.',
      read: '3 min',
    },
    {
      tag: 'API',
      icon: IconBraces,
      title: 'Assert on the database, not only the response',
      body: 'A 200 OK only means the server did not crash. Open the DB, verify the side effect. That is the difference between functional and integration testing.',
      read: '4 min',
    },
    {
      tag: 'Load',
      icon: IconGauge,
      title: 'Think in p95, not averages',
      body: 'Averages mask the 5% of users having a terrible time. Design every load-test report around p95 and p99 latency. Single number SLOs produce single number answers.',
      read: '3 min',
    },
    {
      tag: 'CI/CD',
      icon: IconGitBranch,
      title: 'Fail fast, retry smart',
      body: 'Run unit tests before e2e. Retry only known-flaky specs with a cap of 2. Never retry assertion failures — they are bugs, not noise.',
      read: '2 min',
    },
    {
      tag: 'Culture',
      icon: IconSparkle,
      title: 'Write the bug report you want to receive',
      body: 'Steps, expected, actual, environment, logs, a 10s screen recording. A clear ticket saves 40 minutes of back-and-forth and earns engineering trust.',
      read: '2 min',
    },
  ],

  socials: {
    linkedin: { url: 'https://www.linkedin.com/in/farhadpasha', handle: 'linkedin.com/in/farhadpasha' },
    github: { url: 'https://github.com/FarhadPashayev', handle: 'github.com/FarhadPashayev' },
    email: { url: 'mailto:pasaferhad@gmail.com', handle: 'pasaferhad@gmail.com' },
  },
};
